# Generated by Django 4.0.5 on 2022-06-21 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_members_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 6, 21)),
        ),
    ]
