# Generated by Django 4.0.5 on 2022-06-21 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date(2022, 6, 21))),
            ],
        ),
    ]
